### ISSUE TITLE
Latest update to coc.nvim breaks coc-conjure integration.

### ISSUE THREAD

**Issue by dharrigan** [jlesquembre/coc-conjure#16]
A new error after this release:

`https://github.com/neoclide/coc.nvim/commit/dc5658295848564b388faed642017919da12f840`

The current integration is borked with coc-conjure.

![coc-conjure-error](https://user-images.githubusercontent.com/427150/153620160-2d025734-a0ed-4938-b352-d5d2561a2faf.png)

A PR is on it's way...

**Comment by daveyarwood** [comment]
I ran into the same issue. Confirmed that the problem went away after upgrading coc-conjure. Thanks @dharrigan and @jlesquembre ! :tada:
