### ISSUE TITLE
Instructions on installation usage

### ISSUE THREAD

**Issue by BerkeleyTrue** [jlesquembre/coc-conjure#6]
I can't get this extension to run.

I'm also at a lost at how to debug.

Doesn't trigger with Clojure or Fennel files.

Conjure itself does work through mappings and nvim commands.

Other Coc extensions do work in the same files

NVIM version
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5

```

coc 
```
vim version: NVIM v0.4.4
node version: v12.18.4
coc.nvim version: 0.0.79-b71489207a
coc.nvim directory: /home/berkeleytrue/.config/nvim/plugged/coc.nvim
term: screen-256color
platform: linux
```

coc settings (changing/removing the conjure settings has no effect).
```
{
  "javascript.suggestionActions.enabled": false,
  "javascript.validate.enable": false,

  "eslint.autoFixOnSave": true,

  "coc.source.conjure.enable": true,
  "coc.source.conjure.shortcut": "CLR",
  "coc.source.conjure.filetypes": [
    "clojure",
    "fennel"
  ],

  "languageserver": {
    "terraform": {
      "command": "terraform-lsp",
      "filetypes": ["terraform"],
      "initializationOptions": {}
    }
  }
}

```

conjure

```
Plug 'olical/conjure', {'tag': 'v4.5.0'}
```

**Comment by jlesquembre** [comment]
Do you have a nrepl connection? Not sure why isn't working for you. You don't need to add anything to your coc-settings.json file, in fact, that options don't change anything. You only need to do one of the two things mention on the readme:

```
let g:coc_global_extensions = ['coc-conjure']
```

or

```
:CocInstall coc-conjure
```

As an example, I used the first option, and it works, you can see my dotfiles: 

https://github.com/jlesquembre/dotfiles/blob/master/nvim/init.vim#L1893-L1908

**Comment by BerkeleyTrue** [comment]
yes, there is an nrepl connection. I can use conjure directly from vim. I'm just not getting any completion or any indication that coc-conjure is running though CocInfo.

Yes, it is installed.

Any ideas on how to debug?

```
let g:coc_global_extensions = [
      \ 'coc-conjure',
      \ 'coc-elixir',
      \ 'coc-css',
      \ 'coc-dictionary',
      \ 'coc-emmet',
      \ 'coc-emoji',
      \ 'coc-eslint',
      \ 'coc-git',
      \ 'coc-html',
      \ 'coc-jest',
      \ 'coc-json',
      \ 'coc-omni',
      \ 'coc-prettier',
      \ 'coc-rls',
      \ 'coc-snippets',
      \ 'coc-stylelint',
      \ 'coc-tag',
      \ 'coc-tsserver',
      \ 'coc-vetur',
      \ 'coc-word',
      \ 'coc-yaml',
      \ 'coc-yank']

```

```
- ✓ coc-conjure Current version 3.0.0 is up to date.  
- ✓ coc-css Current version 1.2.5 is up to date.      
- ✓ coc-dictionary Current version 1.2.2 is up to date
- ✓ coc-elixir Current version 0.5.2 is up to date.   
- ✓ coc-emmet Current version 1.1.6 is up to date.    
- ✓ coc-emoji Current version 1.2.3 is up to date.    
- ✓ coc-eslint Current version 1.3.1 is up to date.   
- ✓ coc-git Current version 2.0.1 is up to date.      
- ✓ coc-html Current version 1.2.4 is up to date.     
- ✓ coc-jest Current version 1.0.4 is up to date.     
- ✓ coc-json Current version 1.3.1 is up to date.     
- ✓ coc-omni Current version 1.2.4 is up to date.     
- ✓ coc-prettier Current version 1.1.17 is up to date.
- ✓ coc-rls Current version 1.1.6 is up to date.      
- ✓ coc-snippets Current version 2.2.0 is up to date. 
- ✓ coc-stylelint Current version 1.1.0 is up to date.
- ✓ coc-tag Current version 1.2.5 is up to date.      
- ✓ coc-tsserver Current version 1.5.7 is up to date. 
- ✓ coc-vetur Current version 1.2.0 is up to date.    
- ✓ coc-word Current version 1.2.2 is up to date.     
- ✓ coc-yaml Current version 1.0.5 is up to date.     
- ✓ coc-yank Current version 1.1.5 is up to date.
```

![image](https://user-images.githubusercontent.com/6775919/93919686-e1c72080-fcc2-11ea-8cda-bb2855755dc0.png)

CocLog
```
2020-09-22T10:59:26.108 INFO (pid:468547) [services] - registered service "languageserver.terraform"
2020-09-22T10:59:26.138 INFO (pid:468547) [services] - registered service "eslint"
2020-09-22T10:59:26.311 INFO (pid:468547) [plugin] - coc.nvim 0.0.79-d2a3186309 initialized with node: v12.18.4 after 274ms
```
CocInfo
```
## versions

vim version: NVIM v0.4.4
node version: v12.18.4
coc.nvim version: 0.0.79-d2a3186309
coc.nvim directory: /home/berkeleytrue/.config/nvim/plugged/coc.nvim
term: screen-256color
platform: linux

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root of /home/berkeleytrue/dvlpmnt/clojure/todo/src/cljs/todo/views.cljs: /home/berkeleytrue/dvlpmnt/clojure/todo
> git ls-files -- src/cljs/todo/views.cljs
> git --no-pager show :src/cljs/todo/views.cljs
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git diff src/cljs/todo/views.cljs

## Output channel: prettier


## Output channel: snippets

[Info 11:01:37 AM] Using ultisnips directories: UltiSnips /home/berkeleytrue/.config/coc/ultisnips
[Info 11:01:37 AM] Using ultisnips python command: pyx


```

**Comment by jlesquembre** [comment]
Maybe you can try `:CocList extensions` and verify that coc-conjure is enabled (you should see a `*` if the extension is enabled)

I checked my CoC logs, even if the plugin is working, there is nothing on the logs.

My CocLog output, I'm running an older version, maybe something broke on the last CoC version?
 
```
## versions

vim version: NVIM v0.4.3
node version: v12.15.0
coc.nvim version: 0.0.78-bdd9a9e140
term: alacritty
platform: linux
```

What you can do for debugging is to install the plugin as explained here: https://github.com/jlesquembre/coc-conjure#development
and then, you can start to add `console.log` statements on the index.js file to see what's going on, usually I debug it that way.

**Comment by BerkeleyTrue** [comment]
It seems to be enabled.

![image](https://user-images.githubusercontent.com/6775919/93948581-af81e700-fcf3-11ea-8e5d-5944130f38c6.png)

I don't see any completions showing up though.

![image](https://user-images.githubusercontent.com/6775919/93948662-dc35fe80-fcf3-11ea-8583-0a1d7eb07670.png)

Later today I'll try to pin to the version oc CoC you are using to see if I get anything.

**Comment by BerkeleyTrue** [comment]
I'm able to get something in the coc log to show up. 

```
2020-09-23T19:46:06.406 INFO (pid:1738317) [plugin] - coc.nvim 0.0.79-d2a3186309 initialized with node: v12.18.4 after 333ms
2020-09-23T19:46:43.532 INFO (pid:1738317) [completion-complete] - Results from: around,buffer,word,conjure,tmuxcomplete
2020-09-23T19:46:44.292 INFO (pid:1738317) [completion-complete] - Results from: word,conjure,tmuxcomplete
```

But I'm still not seeing anything show up in the popupmenu or seeing any of the console logs I'm adding to coc-conjure/index file under coc/extensions

**Comment by BerkeleyTrue** [comment]
No luck trying to get an older version of coc to run.

**Comment by BerkeleyTrue** [comment]
Alright, I'm finally able to get some visibility:
![image](https://user-images.githubusercontent.com/6775919/94098468-8178d180-fddd-11ea-85d6-64ab7e2332d8.png)

That's a print out of the results coming back for defn, but it seems no matter what the input is the results are always the same. Not sure how coc decides what to show after being returned from this function.

Where does the documentation live for the nvim api?

**Comment by BerkeleyTrue** [comment]
alright, looks like I've found the issue:

![image](https://user-images.githubusercontent.com/6775919/94101125-1ed70400-fde4-11ea-9459-f7d9870c4eb4.png)


Seems like the api for doComplete has changed:

Here is the fix:

```js
exports.activate = async (context) => {
  context.subscriptions.push(
    sources.createSource({
      name: "conjure",
      triggerCharacters: [".", "/", ":"],
      doComplete: async function (opt) {
        const input = opt.input;
        if (!input) return null;
        const res = await completions(input);
        if (!res || res.length === 0) return null;
        return {
          items: res.map((word) => ({
            word,
            menu: this.menu,
          })),
        };
      },
    })
  );
};
```

Coc expects an array of objects to be returned. This this.menu is important to show the shortcut text.

Would you like a PR?

**Comment by jlesquembre** [comment]
thanks for digging into this, great work. I didn't find anything on the release notes, but I found that the same change was done in the "official" plugins:
https://github.com/neoclide/coc-sources/blob/master/packages/dictionary/index.js

If you want to create a PR, I'll merge it, but if not, I can just pick the changes, up to you, for me is the same effort.

The only issue is that I don't have much time, I'll try to find time this (or next) weekend to test it and create a new release

**Comment by BerkeleyTrue** [comment]
ready for ya
