### ISSUE TITLE
not getting any completion info out

### ISSUE THREAD

**Issue by BerkeleyTrue** [jlesquembre/coc-conjure#8]
Looks like this commit https://github.com/jlesquembre/coc-conjure/commit/25e672e32deaaf06c06951c5961560ac9b4e322d#diff-168726dbe96b3ce427e7fedce31bb0bcL36

Is breaking the api.

**Comment by jlesquembre** [comment]
It can be the `...` syntax. What's is your node version?

**Comment by BerkeleyTrue** [comment]
Doesn't work with either Node 12 or 14. Did conjure change it's eval api results? I'm still a list of strings, not objects. 

![image](https://user-images.githubusercontent.com/6775919/94838697-cd71da80-03ca-11eb-9915-5a808ad2bbca.png)

**Comment by Olical** [comment]
I haven't changed the structure of eval results for as long as I can remember :smile:

**Comment by BerkeleyTrue** [comment]
I think the spread operator was added in error? 
![image](https://user-images.githubusercontent.com/6775919/94851305-2185ba80-03dd-11eb-8557-dadb3a824275.png)

**Comment by jlesquembre** [comment]
Can you log the `res` value?
 https://github.com/jlesquembre/coc-conjure/blob/25e672e32deaaf06c06951c5961560ac9b4e322d/index.js#L37

It should be a list of objects with this shape:
```js
  {
    word: 'inc',
    menu: '[CLJ]',
    info: 'clojure.core/inc\n' +
      '([x])\n' +
      '  Returns a number one greater than num. Does not auto-promote\n' +
      "  longs, will throw on overflow. See also: inc'\n",
    kind: 'F'
  },
```
But maybe CoC is expecting something different in the latest version? The reason I added the `...` is to not lose the `info` and `kind` keys

**Comment by jlesquembre** [comment]
BTW, this is how it looks in my computer:
![screenshot__2020-10-01_213648](https://user-images.githubusercontent.com/1058504/94855223-769dec80-042e-11eb-848d-06517dd14a1c.png)

**Comment by BerkeleyTrue** [comment]
Ok, I've figured it out. It looks like fennel files will give you just an array of strings, while clojure files will give you full items. I've got a fix for ya.

**Comment by Olical** [comment]
Oh damn! That's not great! That inconsistency should be fixed, I feel like array of tables / maps is the way to go? This can definitely be an issue raised against Conjure. Although I don't produce any completions for Fennel, so I just need to ensure all completions flowing out of Conjure get wrapped in a consistent way.

**Comment by Olical** [comment]
I've pushed a change to develop that ensures _every_ client provides completions wrapped in at least `{word: ...}`, I hope that helps! So it'll always be a table/map now, no more string shorthand.

**Comment by BerkeleyTrue** [comment]
Should I close my PR, then? Is there a way to ensure this library has a dependency on a specific version of conjure?

**Comment by jlesquembre** [comment]
Thanks @Olical !
@BerkeleyTrue Since the issue should be solved with next conjure release, let's wait until is released to close the PR

**Comment by jlesquembre** [comment]
See https://github.com/jlesquembre/coc-conjure/pull/9#issuecomment-706992487
